---
  - name: remove previous entries in /etc/hosts
    lineinfile:
     path: /etc/hosts
     regexp: '^(.*){{ ssp_prefix }}.{{ ssp_domain }}'
     state: absent
    ignore_errors: yes

  - name: add DNS name for SSP
    lineinfile:
      dest=/etc/hosts
      line="{{ master_ip }} {{ ssp_prefix }}.{{ ssp_domain }}"