---
  - name: Download Helm
    get_url:
      url: https://get.helm.sh/helm-v3.2.0-linux-amd64.tar.gz
      dest: /tmp
      mode: 0777

  - name: unarchive Helm tar
    unarchive:
      src: /tmp/helm-v3.2.0-linux-amd64.tar.gz
      dest: /tmp
      remote_src: yes

  - name: move helm to /usr/bin
    command: mv /tmp/linux-amd64/helm /usr/bin/
