---
  - name: Ensure firewalld is stopped
    service:
      name: firewalld
      state: stopped
      masked: yes
      enabled: False

  - name: Disabling Swap on all nodes
    shell: swapoff -a
    become: yes

  - name: Commenting Swap entries in /etc/fstab
    replace:
     path: /etc/fstab
     regexp: '(.*swap*)'
     replace: '#\1'
     